# This is a scheduled workflow to keep a copy of the NVD database

name: Update database

on:
  # schedule:
    # Runs at 02:20 UTC everyday
    # - cron: '20 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

permissions:
  pull-requests: write
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install git+https://github.com/intel/cve-bin-tool

      - name: Try single CLI run of tool
        run: |
          python -m cve_bin_tool.cli . -u now

      - name: Dump private key from github secrets
        run: |
          echo '${{ secrets.GPG_PRIVATE_KEY }}' > key.asc
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          chmod 700 ~/.ssh/

      - name: Move json files to the right place
        run: |
          mkdir -p json_feed
          mv ~/.cache/cve-bin-tool/*.json.gz json_feed

      - name: Export database
        run: |
          python -m cve_bin_tool.cli --export-json . --pgp-sign key.asc --passphrase '${{ secrets.PASSPHRASE }}'

      - name: Delete .git and private key
        run: |
          rm -rf key.asc .git

      - name: Push changes
        run: |
          git init .
          git config --global user.email "aniflix.eu.org@gmail.com"
          git config --global user.name "b31ngd3v-bot"
          git checkout -b main
          git add .
          git commit -m "chore: create copy of NVD database"
          git remote add origin 'git@github.com:sec-data/mirror-sandbox.git'
          git push origin main -f
