# This is a scheduled workflow to keep a copy of the NVD database

name: Update database

on:
  schedule:
    # Runs at 00:20 UTC everyday
    - cron: '20 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install git+https://github.com/intel/cve-bin-tool

      - name: Try single CLI run of tool
        run: |
          python -m cve_bin_tool.cli -u now test/assets/test-kerberos-5-1.15.1.out

      - name: Export database
        run: |
          python -m cve_bin_tool.cli --export-json exported_data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: update database copy'
          title: 'chore: create copy of NVD database'
          branch: chore-update_database-copy
          delete-branch: true
          author: GitHub <noreply@github.com>
